// Code generated by goctl. DO NOT EDIT.
package types

type BizTagData struct {
	Id          uint   `json:"id"`
	BizTag      string `json:"biz_tag"`
	Description string `json:"description"` // 描述
	MaxID       int64  `json:"max_id"`
	Step        int64  `json:"step"`
}

type CreateBizTagRequest struct {
	BizTag      string `json:"biz_tag"`
	Description string `json:"description"` // 描述
	MaxID       int64  `json:"max_id"`
	Step        int64  `json:"step,optional,default=100"`
}

type CreateBizTagResponse struct {
	Id uint `json:"id"`
}

type DecodeSnowflakeRequest struct {
	Id int64 `form:"id"`
}

type DecodeSnowflakeResponse struct {
	NodeID    int    `json:"node_id"`
	Epoch     int64  `json:"epoch"`
	Time      string `json:"time"`
	Timestamp int64  `json:"timestamp"`
	Sequence  int    `json:"sequence"`
}

type DeletedBizTagResponse struct {
}

type DeletedBizTageRequest struct {
	Id uint `json:"id"`
}

type GetBizTagResponse struct {
	Id          uint   `json:"id"`
	BizTag      string `json:"biz_tag"`
	Description string `json:"description"` // 描述
	MaxID       int64  `json:"max_id"`
	Step        int64  `json:"step"`
}

type GetBizTageRequest struct {
	Id uint `form:"id"`
}

type ListBizTagResponse struct {
	Total int64         `json:"total"`
	List  []*BizTagData `json:"list"`
}

type ListBizTageRequest struct {
	Page     int `form:"page,optional,default=1"`
	PageSize int `form:"page_size,optional,default=10"`
}

type SegmentRequest struct {
	BizTag string `form:"biz_tag"`
}

type SegmentResponse struct {
	MinID int64 `json:"min_id"`
	MaxID int64 `json:"max_id"`
	Step  int64 `json:"step"`
}

type SnowflakeRequest struct {
	Step int64 `form:"step,optional,default=50"`
}

type SnowflakeResponse struct {
	Total int64   `json:"total"`
	List  []int64 `json:"list"`
}

type UpdateBizTagResponse struct {
	BizTag      string `json:"biz_tag"`
	Description string `json:"description"` // 描述
	MaxID       int64  `json:"max_id"`
	Step        int64  `json:"step"`
}

type UpdateBizTageRequest struct {
	Id          uint   `json:"id"`
	Description string `json:"description,optional"` // 描述
	Step        int64  `json:"step,optional"`
}
